// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://xplzouxqwtsunfovfvht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhwbHpvdXhxd3RzdW5mb3Zmdmh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDkzMzgwODEsImV4cCI6MjA2NDkxNDA4MX0.qP5MNmsfp2wWhUJtXXK-gHTyqEtSUBBkLcBQJD0zDB4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);